# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  microwin:
    image: microwin
    build:
      context: .
      dockerfile: ./DockerDebugfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ENV=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
