# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  microwin:
    image: microwin
    env_file: 
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:5000
    volumes:
      - dbdata:/data
    
volumes: 
  dbdata: