# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  microwin:
    image: microwin
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000
    volumes:
      - dbdata:/data
      - ./SeverApp/App_Data:/app/App_Data/

volumes: 
  dbdata: