# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  clientapp:
    image: clientapp
    build:
      context: ClientApp
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  microwin:
    image: micro-cowin
    env_file: 
      - ./ServerApp/.env
    build:
      context: .
      dockerfile: ./ServerApp/Dockerfile
    ports:
      - 5000
    volumes:
      - dbdata:/data
    
volumes: 
  dbdata: