CREATE TABLE Vax(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO
    Vax (Name)
VALUES
    ('Covishield');

INSERT INTO
    Vax (Name)
VALUES
    ('Covaxin');